# Generated by Django 3.1.3 on 2020-11-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('genre_id', models.IntegerField()),
                ('overview', models.TextField()),
                ('released', models.DateField()),
                ('vote', models.IntegerField()),
                ('poster', models.CharField(max_length=500)),
                ('backdrop', models.CharField(max_length=500)),
                ('adult', models.BooleanField(default=False)),
            ],
        ),
    ]
