# Generated by Django 3.1.3 on 2020-11-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_genres',
            field=models.ManyToManyField(related_name='genre_movies', to='reviews.Genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_themes',
            field=models.ManyToManyField(related_name='theme_movies', to='reviews.Theme'),
        ),
    ]
