# Generated by Django 3.1.3 on 2020-11-22 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20201120_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre_id',
            new_name='uniq_id',
        ),
    ]
