# Generated by Django 3.1.3 on 2020-11-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20201122_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='uniq_id',
            new_name='unique_id',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_id',
            new_name='popularity',
        ),
        migrations.AddField(
            model_name='movie',
            name='unique_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
