# Generated by Django 3.1.3 on 2020-11-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20201123_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='backdrop',
            new_name='backdrop_path',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='poster',
            new_name='poster_path',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='released',
            new_name='release_date',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='popularity',
            new_name='vote_average',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='vote',
        ),
        migrations.AddField(
            model_name='movie',
            name='video_path',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
