# Generated by Django 3.1.3 on 2020-11-23 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20201123_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video_path',
        ),
    ]
