# Generated by Django 3.1.3 on 2020-11-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_remove_movie_video_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='vote_average',
            field=models.FloatField(),
        ),
    ]
