# Generated by Django 3.1.3 on 2020-11-20 06:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20201120_1512'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followings',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='user_genres',
            field=models.ManyToManyField(related_name='genre_users', to='reviews.Genre'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_themes',
            field=models.ManyToManyField(related_name='theme_users', to='reviews.Theme'),
        ),
    ]
